server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: uereka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jieve-ad-data?autoReconnect=true
    username: root
    data-password: 123456
    tomcat:
      max-active: 10
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/